# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled4.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *
class Ui_MainWindow(QMainWindow):
    def __init__(self):  # 添加初始化函数
        super(Ui_MainWindow, self).__init__()
        self.setupUi(self)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 30, 72, 15))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 80, 451, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(160, 310, 491, 91))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(240, 390, 341, 91))
        self.pushButton_7.setObjectName("pushButton_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(self.getbal)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_3.clicked.connect(lambda :self.addbal(50))
        self.pushButton_4.clicked.connect(lambda: self.addbal(100))
        self.pushButton_5.clicked.connect(lambda: self.addbal(200))
        self.pushButton_6.clicked.connect(lambda: self.addbal(500))
        self.pushButton_7.clicked.connect(self.setvip)
    def getbal(self):
        import db_use
        usernmae=self.lineEdit_2.text()
        print(usernmae)
        if len(usernmae)==0:
            reply = QMessageBox.warning(self, '出现一个问题', '用户名为填写', QMessageBox.Yes | QMessageBox.No,QMessageBox.Yes)
        if not db_use.hasowner(usernmae):
            print(111)
            reply = QMessageBox.warning(self, '错误', '用户不存在', QMessageBox.Yes | QMessageBox.No,QMessageBox.Yes)
        else:
            userid=db_use.getowner(usernmae)
            print(userid)
            cash=db_use.getbalance(userid)
            self.lineEdit.setText(str(cash))
    def addbal(self,num):
        import db_use
        usernmae = self.lineEdit_2.text()
        print(usernmae)
        if len(usernmae) == 0:
            reply = QMessageBox.warning(self, '出现一个问题', '用户名为填写', QMessageBox.Yes | QMessageBox.No,
                                        QMessageBox.Yes)
        if not db_use.hasowner(usernmae):
            print(111)
            reply = QMessageBox.warning(self, '错误', '用户不存在', QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
        else:
            userid = db_use.getowner(usernmae)
            db_use.addbalance(userid,num)
            reply = QMessageBox.information(self, '成功', '成功充值'+str(num)+'￥', QMessageBox.Yes | QMessageBox.No,
                                            QMessageBox.Yes)
    def setvip(self):
        import db_use
        usernmae = self.lineEdit_2.text()
        print(usernmae)
        if len(usernmae) == 0:
            reply = QMessageBox.warning(self, '出现一个问题', '用户名为填写', QMessageBox.Yes | QMessageBox.No,
                                        QMessageBox.Yes)
        if not db_use.hasowner(usernmae):
            print(111)
            reply = QMessageBox.warning(self, '错误', '用户不存在', QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
        else:
            userid = db_use.getowner(usernmae)
            db_use.setvip(userid)
            reply = QMessageBox.information(self, '成功', '成功充值vip', QMessageBox.Yes | QMessageBox.No,
                                            QMessageBox.Yes)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "充值界面"))
        self.label_3.setText(_translate("MainWindow", "输入车主名"))
        self.pushButton_2.setText(_translate("MainWindow", "确认"))
        self.label_2.setText(_translate("MainWindow", "余额"))
        self.pushButton.setText(_translate("MainWindow", "查询余额"))
        self.pushButton_3.setText(_translate("MainWindow", "充值50￥"))
        self.pushButton_4.setText(_translate("MainWindow", "充值100￥"))
        self.pushButton_5.setText(_translate("MainWindow", "充值200￥"))
        self.pushButton_6.setText(_translate("MainWindow", "充值500￥"))
        self.pushButton_7.setText(_translate("MainWindow", "购买停车位，享VIP免费停车"))
