# -*- coding: utf-8 -*-
import json

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *

import get_img
import getmask
import ocr

class Ui_MainWindow(QMainWindow):
    def __init__(self):  # 添加初始化函数
        super(Ui_MainWindow, self).__init__()
        self.setupUi(self)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1142, 834)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 1121, 281))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(260, 320, 531, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(800, 320, 160, 100))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 400, 111, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(310, 420, 431, 361))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_6.addWidget(self.lineEdit_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(260, 360, 531, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_7.addWidget(self.lineEdit_7)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(810, 590, 281, 141))
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1142, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton_2.clicked.connect(self.getcam)
        self.pushButton_3.clicked.connect(self.recognize)
        self.pushButton_4.clicked.connect(self.cartype)
        self.pushButton_6.clicked.connect(self.submit)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.centralwidget.setStyleSheet("""
                      #centralwidget{  
                      background-image: url('5.jpg');
                      background-size: cover;
                      background-repeat: no-repeat;
                      background-position: center;
                      }
               
        """)

        with open("carinfo.json","r")as file:
            car_info=json.load(file)
            # print(car_info)
            if car_info["cap"]:
                self.lineEdit.setText(car_info["plate"])
                self.label_2.setText(car_info["info"])
                self.label_2.adjustSize()
                self.pushButton_6.setText("确认进行注册")
                self.label.setPixmap(QPixmap("CAR_RAW.jpg"))
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "车辆识别"))
        self.pushButton.setText(_translate("MainWindow", "确认"))
        self.pushButton_2.setText(_translate("MainWindow", "拍照/重拍"))
        self.pushButton_3.setText(_translate("MainWindow", "识别车牌"))
        self.pushButton_4.setText(_translate("MainWindow", "识别车型"))
        self.label_2.setText(_translate("MainWindow", "车主信息登记"))
        self.label_3.setText(_translate("MainWindow", "车主姓名"))
        self.label_5.setText(_translate("MainWindow", "车主备注"))
        self.label_6.setText(_translate("MainWindow", "车主年龄"))
        self.label_7.setText(_translate("MainWindow", "车主住址"))
        self.label_4.setText(_translate("MainWindow", "车主性别"))
        self.pushButton_5.setText(_translate("MainWindow", "确认"))
        self.pushButton_6.setText(_translate("MainWindow", "确认提交"))
        self.label.setStyleSheet("color: white; font-size: 18px;")
        self.label_2.setStyleSheet("color: white; font-size: 18px;")
        self.label_3.setStyleSheet("color: white; font-size: 18px;")
        self.label_4.setStyleSheet("color: white; font-size: 18px;")
        self.label_5.setStyleSheet("color: white; font-size: 18px;")
        self.label_6.setStyleSheet("color: white; font-size: 18px;")
        self.label_7.setStyleSheet("color: white; font-size: 18px;")
    def getcam(self):
        self.pushButton_3.setEnabled(False)
        get_img.Getimg(self.label.width(), self.label.height())
        self.label.setPixmap(QPixmap("cap.jpg"))
        self.pushButton_3.setEnabled(True)
    def recognize(self):
        nums = getmask.Getmask("cap_raw.jpg")
        print(nums)
        dist = "plate/CAR_" + str(nums) + ".jpg"
        if nums == -1:
            self.label.setPixmap(QPixmap("notfound.png"))
        else:

            self.label.setPixmap(QPixmap("CAR_RAW.jpg"))
            PLATE = ocr.OCR_detail()
            print(PLATE)
            # 识别识别就拿识别到的最大的框中的内容作为识别结果
            if len(PLATE) == 0:
                PLATE = ocr.OCR_raw(dist)
                self.lineEdit.setText(PLATE)
            else:
                self.lineEdit.setText(PLATE)

    def cartype(self):
        import cartype
        tmp=cartype.baidu_detect("cap_raw.jpg")
        self.lineEdit_7.setText(tmp)
    def  submit(self):

        ans=dict()
        ans["plate"]=self.lineEdit.text()
        ans["cartype"] = self.lineEdit_7.text()
        ans["owner"]=self.lineEdit_2.text()
        ans["age"] = self.lineEdit_5.text()
        ans["address"] = self.lineEdit_6.text()
        ans["sex"] = self.lineEdit_3.text()
        if  ans["sex"]=='男':
            ans["sex"] = 'm'
        if ans["sex"] == '女':
            ans["sex"] = 'f'
        flag=False
        import db_use
        if db_use.hasowner(ans["owner"]):
            flag=True
        for key,val in ans.items():
            if len(val)==0:
                flag=True
        if flag:
            if db_use.hasowner(ans["owner"]):
                reply = QMessageBox.warning(self, '错误', '该用户名已存在', QMessageBox.Yes | QMessageBox.No,
                                            QMessageBox.Yes)
            else:
                reply = QMessageBox.warning(self, '错误', '请填写所有信息', QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
        else:
            import db_use
            db_use.createuser(ans["owner"],ans["sex"],ans["age"],ans["address"])
            id=db_use.getowner(ans["owner"])
            db_use.createcar(ans["plate"],ans["cartype"],id)
            db_use.createaccount(id,0,False)
            nums=db_use.hascartype(ans["cartype"])
            if nums==0:
                import cartype_to_ishigh
                import db_use
                ishigh=cartype_to_ishigh.baidu_ishigh("cap_raw.jpg")
                db_use.createcartype(ans["cartype"],ishigh)
            reply = QMessageBox.information(self, '成功', '成功创建新用户', QMessageBox.Yes | QMessageBox.No,
                                        QMessageBox.Yes)
